from enum import Enum
import sys, inspect

class Keys:

    class Battery(Enum):
        AGGREGATION_STATE = 'Battery/0/AggregationState'
        BATTERY_EMBED_OK = 'Battery/0/BatteryEmbedOK'
        BATTERY_LEDS_ENABLED = 'Battery/0/BatteryLEDsEnabled'
        BATTERY_TYPE = 'Battery/0/BatteryType'
        CELL_VOLTAGES = 'Battery/0/CellVoltages'
        CELL_VOLTAGE_LEVEL = 'Battery/0/CellVoltageLevel'
        CHARGE_REMAINING = 'Battery/0/ChargeRemaining'
        CHARGE_REMAINING_IN_PERCENT = 'Battery/0/ChargeRemainingInPercent'
        CONNECTION_STATE = 'Battery/0/ConnectionState'
        CURRENT = 'Battery/0/Current'
        DESIGN_CAPACITY = 'Battery/0/DesignCapacity'
        FIRMWARE_VERSION = 'Battery/0/FirmwareVersion'
        FULL_CHARGE_CAPACITY = 'Battery/0/FullChargeCapacity'
        HIGHEST_TEMPERATURE = 'Battery/0/HighestTemperature'
        HISTORICAL_WARNING_RECORDS = 'Battery/0/HistoricalWarningRecords'
        IS_ANY_BATTERY_DISCONNECTED = 'Battery/0/IsAnyBatteryDisconnected'
        IS_BATTERY_SELF_HEATING = 'Battery/0/IsBatterySelfHeating'
        IS_BEING_CHARGED = 'Battery/0/IsBeingCharged'
        IS_BIG_BATTERY = 'Battery/0/IsBigBattery'
        IS_CELL_DAMAGED = 'Battery/0/IsCellDamaged'
        IS_FIRMWARE_DIFFERENCE_DETECTED = 'Battery/0/IsFirmwareDifferenceDetected'
        IS_IN_SINGLE_BATTERY_MODE = 'Battery/0/isInSingleBatteryMode'
        IS_LOW_CELL_VOLTAGE_DETECTED = 'Battery/0/IsLowCellVoltageDetected'
        IS_SMART_BATTERY = 'Battery/0/isSmartBattery'
        IS_VOLTAGE_DIFFERENCE_DETECTED = 'Battery/0/IsVoltageDifferenceDetected'
        LATEST_WARNING_RECORD = 'Battery/0/LatestWarningRecord'
        LEVEL_1_CELL_VOLTAGE_BEHAVIOR = 'Battery/0/Level1CellVoltageBehavior'
        LEVEL_1_CELL_VOLTAGE_THRESHOLD = 'Battery/0/Level1CellVoltageThreshold'
        LEVEL_2_CELL_VOLTAGE_BEHAVIOR = 'Battery/0/Level2CellVoltageBehavior'
        LEVEL_2_CELL_VOLTAGE_THRESHOLD = 'Battery/0/Level2CellVoltageThreshold'
        LIFETIME_REMAINING = 'Battery/0/LifetimeRemaining'
        MANUFACTURE_DATE = 'Battery/0/ManufactureDate'
        NUMBER_OF_CELLS = 'Battery/0/NumberOfCells'
        NUMBER_OF_CONNECTED_BATTERIES = 'Battery/0/NumberOfConnectedBatteries'
        NUMBER_OF_DISCHARGES = 'Battery/0/NumberOfDischarges'
        OVERVIEWS = 'Battery/0/Overviews'
        PAIRING_STATE = 'Battery/0/PairingState'
        PAIR_BATTERIES = 'Battery/0/PairBatteries'
        SELF_DISCHARGE_IN_DAYS = 'Battery/0/SelfDischargeInDays'
        SELF_HEATING_STATE = 'Battery/0/SelfHeatingState'
        SERIAL_NUMBER = 'Battery/0/SerialNumber'
        TEMPERATURE = 'Battery/0/Temperature'
        VOLTAGE = 'Battery/0/Voltage'

    class FlightController(Enum):
        ABSOLUTE_GPS_ALTITUDE = 'FlightController/0/GPSAbsoluteAltitude'
        ACCESS_LOCKER_STATE = 'FlightController/0/AccessLockerState'
        ACCESS_LOCKER_SUPPORTED = 'FlightController/0/AccessLockerSupported'
        ACCESS_LOCKER_USERNAME = 'FlightController/0/AccessLockerUsername'
        ACCESS_LOCKER_VERSION = 'FlightController/0/AccessLockerVersion'
        ACTIVE_BRAKE_ENGAGED = 'FlightController/0/ActiveBrakeEngaged'
        ACTIVE_OBSTACLE_AVOIDANCE_ENABLED = 'FlightController/0/ActiveAvoidanceEnabled'
        ACTIVE_TRACK_CAMERA = 'FlightController/0/ActiveTrackCamera'
        ACTIVE_TRACK_CAMERA_STREAM = 'FlightController/0/ActiveTrackCameraStream'
        ACTIVE_TRACK_CIRCULAR_SPEED = 'FlightController/0/ActiveTrackCircularSpeed'
        ACTIVE_TRACK_GESTURE_MODE_ENABLED = 'FlightController/0/AdvancedGestureControlEnabled'
        ACTIVE_TRACK_GPS_ASSISTANT_ENABLED = 'FlightController/0/ActiveTrackGPSAssistantEnabled'
        ACTIVE_TRACK_MODE = 'FlightController/0/ActiveTrackMode'
        ADVANCED_GESTURE_CONTROL_ENABLED = 'FlightController/0/AdvancedGestureControlEnabled'
        AIRCRAFT_GO_HOME_COUNT_DOWN = 'FlightController/0/AircraftGoHomeCountDown'
        AIRCRAFT_LOCATION = 'FlightController/0/AircraftLocation'
        AIRCRAFT_LOCATION_LATITUDE = 'FlightController/0/AircraftLocationLatitude'
        AIRCRAFT_LOCATION_LONGITUDE = 'FlightController/0/AircraftLocationLongitude'
        AIRCRAFT_NAME = 'FlightController/0/AircraftName'
        AIRCRAFT_SHOULD_GO_HOME = 'FlightController/0/AircraftShouldGoHome'
        AIRCRAFT_TOTAL_FLIGHT_DISTANCE = 'FlightController/0/AircraftTotalFlightDistance'
        AIRCRAFT_TOTAL_FLIGHT_DURATION = 'FlightController/0/AircraftTotalFlightDuration'
        AIRCRAFT_TOTAL_FLIGHT_TIMES = 'FlightController/0/AircraftTotalFlightTimes'
        AIR_SENSE_AIRPLANE_STATES = 'FlightController/0/AirSenseAirplaneStates'
        AIR_SENSE_SYSTEM_CONNECTED = 'FlightController/0/AirSenseSystemConnected'
        AIR_SENSE_SYSTEM_WARNING_LEVEL = 'FlightController/0/AirSenseSystemWarningLevel'
        ALTITUDE = 'FlightController/0/Altitude'
        APAS_STATE = 'FlightController/0/APASState'
        ARE_MOTOR_ON = 'FlightController/0/AreMotorsOn'
        ATTITUDE_PITCH = 'FlightController/0/AttitudePitch'
        ATTITUDE_ROLL = 'FlightController/0/AttitudeRoll'
        ATTITUDE_YAW = 'FlightController/0/AttitudeYaw'
        BATTERY_PERCENTAGE_NEEDED_TO_GO_HOME = 'FlightController/0/BatteryPercentageNeededToGoHome'
        BATTERY_THRESHOLD_BEHAVIOR = 'FlightController/0/RemainingBattery'
        BINDING_STATE = 'FlightController/0/BindingState'
        BOTH_CONTROL_MULTI_GIMBALS = 'FlightController/0/both_control_multi_gimbals'
        BOTTOM_AUXILIARY_LIGHT_MODE = 'FlightController/0/BottomAuxiliaryLightMode'
        CANCEL_GO_HOME = 'FlightController/0/CancelGoHome'
        CANCEL_LANDING = 'FlightController/0/CancelAutoLanding'
        CANCEL_TAKE_OFF = 'FlightController/0/CancelTakeOff'
        CINEMATIC_BRAKE_SENSITIVITY = 'FlightController/0/CinematicBrakeSensitivity'
        CINEMATIC_BRAKE_SENSITIVITY_RANGE = 'FlightController/0/CinematicBrakeSensitivityRange'
        CINEMATIC_MODE_ENABLED = 'FlightController/0/CinematicModeEnabled'
        CINEMATIC_YAW_SPEED = 'FlightController/0/CinematicYawSpeed'
        CINEMATIC_YAW_SPEED_RANGE = 'FlightController/0/CinematicYawSpeedRange'
        COLLISION_AVOIDANCE_ENABLED = 'FlightController/0/CollisionAvoidanceEnabled'
        COMPASS_CALIBRATION_STATUS = 'FlightController/0/CompassCalibrationStatus'
        COMPASS_COUNT = 'FlightController/0/CompassCount'
        COMPASS_HAS_ERROR = 'FlightController/0/CompassHasError'
        COMPASS_HEADING = 'FlightController/0/CompassHeading'
        COMPASS_IS_CALIBRATING = 'FlightController/0/CompassIsCalibrating'
        COMPASS_START_CALIBRATION = 'FlightController/0/CompassStartCalibration'
        COMPASS_STATE = 'FlightController/0/CompassState'
        COMPASS_STOP_CALIBRATION = 'FlightController/0/CompassStopCalibration'
        CONFIRM_LANDING = 'FlightController/0/confirmLanding'
        CONFIRM_SMART_RETURN_TO_HOME_REQUEST = 'FlightController/0/ConfirmSmartReturnToHomeRequest'
        CONNECTION_FAIL_SAFE_BEHAVIOR = 'FlightController/0/FlightFailSafeOperation'
        CONNECT_TO_BASE_STATION = 'FlightController/0/ConnectToBaseStation'
        CONTROL_GIMBAL_BEHAVIOR = 'FlightController/0/control_gimbal_behavior'
        CONTROL_MODE = 'FlightController/0/ControlMode'
        CURRENT_LAND_IMMEDIATELY_BATTERY = 'FlightController/0/CurrentLandImmediatelyBattery'
        CURRENT_MODE = 'FlightController/0/CurrentMode'
        CUSTOM_FUNCTION_MODE = 'FlightController/0/CustomFunctionMode'
        DEPLOY_LANDING_GEAR = 'FlightController/0/DeployLandingGear'
        DETECTION_SECTORS = 'FlightController/0/DetectionSectors'
        DOES_APAS_HAVE_TEMP_ERROR = 'FlightController/0/DoesAPASHasTempError'
        DRAW_HEADING_MODE = 'FlightController/0/FlightControllerDrawHeadingMode'
        DRAW_STATUS = 'FlightController/0/FlightControllerDrawStatus'
        ENABLE_1860 = 'FlightController/0/Enable1860'
        ENTER_NAVIGATION_MODE = 'FlightController/0/EnterNavigationMode'
        ENTER_TRANSPORT_MODE = 'FlightController/0/EnterTransportMode'
        ESC_BEEPING_ENABLED = 'FlightController/0/ESCBeepingEnabled'
        EXIT_TRANSPORT_MODE = 'FlightController/0/ExitTransportMode'
        FIXED_WING_CONTROL = 'FlightController/0/FixedWingControl'
        FLIGHT_ACTION = 'FlightController/0/FlightAction'
        FLIGHT_CONTROLLER_DYNAMIC_HOME = 'FlightController/0/FlightControllerDynamicHome'
        FLIGHT_CONTROLLER_TRACK_MODE = 'FlightController/0/FlightControllerTrackMode'
        FLIGHT_MODE = 'FlightController/0/FlightMode'
        FLIGHT_MODE_STRING = 'FlightController/0/FlightModeString'
        FLIGHT_WIND_WARNING = 'FlightController/0/FlightWindWarning'
        FLY_TIME_IN_SECONDS = 'FlightController/0/FlyTime'
        FLY_ZONE_LIMITATION_ENABLED = 'FlightController/0/GeoFeatureInSimulatorEnabled'
        FORCE_LANDING_AFTER_FLAT_MODE = 'FlightController/0/forceLandingAfterFlatMode'
        FORCE_LANDING_HEIGHT = 'FlightController/0/ForceLandingHeight'
        FORMAT = 'FlightController/0/Format'
        FORMATTING_STATE = 'FlightController/0/FormattingState'
        GET_WAYPOINT_BREAK_INFO = 'FlightController/0/GetWaypointBreakInfo'
        GO_HOME_ASSESSMENT = 'FlightController/0/GoHomeAssessment'
        GO_HOME_HEIGHT_IN_METERS = 'FlightController/0/GoHomeAltitude'
        GO_HOME_STATUS = 'FlightController/0/GoHomeStatus'
        GPS_SIGNAL_LEVEL = 'FlightController/0/GPSSignalLevel'
        GRAVITY_CENTER_STATE = 'FlightController/0/gravity_center_state'
        HAS_INTERNAL_BEACON_LEDS = 'FlightController/0/HasInternalBeaconLeds'
        HAS_REACHED_MAX_FLIGHT_HEIGHT = 'FlightController/0/HasReachedMaxFlightHeight'
        HAS_REACHED_MAX_FLIGHT_RADIUS = 'FlightController/0/HasReachedMaxFlightRadius'
        HOME_LOCATION = 'FlightController/0/HomeLocation'
        HOME_LOCATION_LATITUDE = 'FlightController/0/HomeLocationLatitude'
        HOME_LOCATION_LONGITUDE = 'FlightController/0/HomeLocationLongitude'
        HOME_LOCATION_USING_CURRENT_AIRCRAFT_LOCATION = 'FlightController/0/HomeLocationUsingCurrentAircraftLocation'
        HOME_POINT_ALTITUDE = 'FlightController/0/HomePointAltitude'
        HOME_POINT_STATE = 'FlightController/0/HomePointState'
        HOTPOINT_MAX_ACCELERATION = 'FlightController/0/FlightControllerConfigHotpointMaxAcceleration'
        HOTPOINT_MIN_RADIUS = 'FlightController/0/FlightControllerConfigHotpointMinRadius'
        IMU_COUNT = 'FlightController/0/ImuCount'
        IMU_STATE = 'FlightController/0/IMUState'
        INIT_IO = 'FlightController/0/InitIo'
        INTELLIGENT_FLIGHT_ASSISTANT_IS_USERAVOID_ENABLE = 'FlightController/0/IsUserAvoidEnable'
        IN_ON_LIMITE_AREA_BOUNDARIES = 'FlightController/0/isOnLimitAreaBoundaries'
        IOSTATE_0 = 'FlightController/0/IOState_0'
        IOSTATE_1 = 'FlightController/0/IOState_1'
        IOSTATE_2 = 'FlightController/0/IOState_2'
        IOSTATE_3 = 'FlightController/0/IOState_3'
        IOSTATE_4 = 'FlightController/0/IOState_4'
        IS_ABSOLUTE_GPS_ALTITUDE_SUPPORT = 'FlightController/0/IsGPSAbsoluteAltitudeSupport'
        IS_ADVANCED_PILOT_ASSISTANT_SYSTEM_ENABLED = 'FlightController/0/IsAdvancedPilotAssistantSystemEnabled'
        IS_APAS_ENABLED = 'FlightController/0/IsAPASEnabled'
        IS_APAS_FUNCTIONING = 'FlightController/0/IsAPASFunctioning'
        IS_ASCENT_LIMITED_BY_OBSTACLE = 'FlightController/0/IsAscentLimitedByObstacle'
        IS_AVOIDING_ACTIVE_OBSTACLE_COLLISION = 'FlightController/0/IsAvoidingActiveObstacleCollision'
        IS_BACK_RADAR_OPEN = 'FlightController/0/IsBackRadarOpen'
        IS_BRAKING = 'FlightController/0/IsBraking'
        IS_FAIL_SAFE = 'FlightController/0/IsFailSafe'
        IS_FLIGHT_ASSISTANT_SUPPORTED = 'FlightController/0/IntelligentFlightAssistantSupported'
        IS_FLYING = 'FlightController/0/IsFlying'
        IS_FRONT_RADAR_OPEN = 'FlightController/0/IsFrontRadarOpen'
        IS_GOING_HOME = 'FlightController/0/IsGoingHome'
        IS_HOME_LOCATION_SET = 'FlightController/0/IsHomeLocationSet'
        IS_IMU_PREHEATING = 'FlightController/0/IsIMUPreheating'
        IS_IN_LANDING_MODE = 'FlightController/0/isInLandingMode'
        IS_LANDING = 'FlightController/0/IsAutoLanding'
        IS_LANDING_CONFIRMATION_NEEDED = 'FlightController/0/isLandingConfirmationNeeded'
        IS_LANDING_GEAR_MOVABLE = 'FlightController/0/IsLandingGearMovable'
        IS_LEFT_RADAR_OPEN = 'FlightController/0/IsLeftRadarOpen'
        IS_LOWER_THAN_BATTERY_WARNING_THRESHOLD = 'FlightController/0/IsLowerThanBatteryWarningThreshold'
        IS_LOWER_THAN_SERIOUS_BATTERY_WARNING_THRESHOLD = 'FlightController/0/IsLowerThanSeriousBatteryWarningThreshold'
        IS_MOTORS_LOCK_BY_APP = 'FlightController/0/IsMotorsLockedByApp'
        IS_MOTOR_STOP_LANDING_MODE = 'FlightController/0/IsMotorStopLandingMode'
        IS_MULTI_TRACKING_ENABLED = 'FlightController/0/IsMultiTrackingEnabled'
        IS_MULTI_TRACKING_EXECUTING = 'FlightController/0/IsMultiTrackingExecuting'
        IS_MULTI_TRACKING_WAITING_CONFIRMATION = 'FlightController/0/IsMultiTrackingWaitingConfirmation'
        IS_NO_GPS_MAX_FLIGHT_HEIGHT_SUPPORTED = 'FlightController/0/IsNoGPSMaxFlightHeightSupported'
        IS_ON_BOARD_SDK_AVAILABLE = 'FlightController/0/IsOnBoardSDKAvailable'
        IS_PERFORMING_PRECISION_LANDING = 'FlightController/0/PreciseLandingState'
        IS_POI2_ENABLED = 'FlightController/0/IsPOI2Enabled'
        IS_PRECISION_TAKE_OFF_SUPPORTED = 'FlightController/0/IsPrecisionTakeoffSupported'
        IS_REBOOT_IN_S_MODE = 'FlightController/0/isRebootInSMode'
        IS_RIGHT_RADAR_OPEN = 'FlightController/0/IsRightRadarOpen'
        IS_RTK_CONNECTED = 'FlightController/0/IsRTKConnected'
        IS_RTK_FUSION_DATA_USABLE = 'FlightController/0/IsRTKFusionDataUsable'
        IS_RTK_SUPPORTED = 'FlightController/0/RtkSupported'
        IS_SIMULATOR_ACTIVE = 'FlightController/0/IsSimulatorStarted'
        IS_SYSTEM_UPGRADE_ABNORMAL = 'FlightController/0/IsSystemUpgradeAbnormal'
        IS_ULTRASONIC_BEING_USED = 'FlightController/0/IsUltrasonicBeingUsed'
        IS_VIRTUAL_STICK_CONTROL_MODE_AVAILABLE = 'FlightController/0/isVirtualStickControlModeAvailable'
        IS_VISION_POSITIONING_SENSOR_BEING_USED = 'FlightController/0/IsVisionPositioningSensorBeingUsed'
        LANDING_GEAR_AUTOMATIC_MOVEMENT_ENABLED = 'FlightController/0/LandingGearAutomaticMovementEnabled'
        LANDING_GEAR_HIDE_ENABLED = 'FlightController/0/LandingGearHideEnabled'
        LANDING_GEAR_MODE = 'FlightController/0/LandingGearMode'
        LANDING_GEAR_STATUS = 'FlightController/0/LandingGearStatus'
        LANDING_PROTECTION_ENABLED = 'FlightController/0/LandingProtectionEnabled'
        LANDING_PROTECTION_STATE = 'FlightController/0/LandingProtectionState'
        LEDS_ENABLED_SETTINGS = 'FlightController/0/LEDsEnabledSettings'
        LOCK_COURSE_USING_CURRENT_HEADING = 'FlightController/0/LockCourseUsingCurrentDirection'
        LOCK_MOTORS = 'FlightController/0/LockMotors'
        LOGIN = 'FlightController/0/login'
        LOW_BATTERY_WARNING_THRESHOLD = 'FlightController/0/LowBatteryWarningThreshold'
        MAX_FLIGHT_HEIGHT = 'FlightController/0/MaxFlightHeight'
        MAX_FLIGHT_HEIGHT_IN_NFZ = 'FlightController/0/MaxFlightHeightInNFZ'
        MAX_FLIGHT_HEIGHT_LIMIT_REASON = 'FlightController/0/MaxFlightHeightLimitReason'
        MAX_FLIGHT_HEIGHT_RANGE = 'FlightController/0/MaxFlightHeightRange'
        MAX_FLIGHT_RADIUS = 'FlightController/0/MaxFlightRadius'
        MAX_FLIGHT_RADIUS_ENABLED = 'FlightController/0/MaxFlightRadiusEnabled'
        MAX_FLIGHT_RADIUS_RANGE = 'FlightController/0/MaxFlightRadiusRange'
        MAX_RADIUS_AIRCRAFT_CAN_FLY_AND_GO_HOME = 'FlightController/0/MaxRadiusAircraftCanFlyAndGoHome'
        MAX_WAYPOINT_NUM = 'FlightController/0/MaxWaypointNum'
        MODIFY_USER_ACCOUNT = 'FlightController/0/modifyUserAccount'
        MOTOR_START_FAILED_STATE = 'FlightController/0/MotorStartFailedState'
        MULTI_MODE_OPEN = 'FlightController/0/MultiModeOpen'
        MULTI_RC_EXECUTE_AIRCRAFT_LOST_LOGIC = 'FlightController/0/MultiRcExecuteAircraftLostLogic'
        MULTI_RC_FLIGHT_CONTROL_AUTH_LOCK = 'FlightController/0/MultiRcFlightControlAuthLock'
        MULTI_RC_FLIGHT_CONTROL_AUTH_LOCK_STATE = 'FlightController/0/MultiRcFlightControlAuthLockState'
        MULTI_RC_FLIGHT_CONTROL_AUTH_OWNER = 'FlightController/0/MultiRcFlightControlAuthOwner'
        MULTI_TRACKING_SUB_MODE = 'FlightController/0/MultiTrackingSubMode'
        NEED_LIMIT_FLIGHT_HEIGHT = 'FlightController/0/NeedLimitFlightHeight'
        NOVICE_MODE_ENABLED = 'FlightController/0/NoviceModeEnabled'
        NO_GPS_MAX_FLIGHT_HEIGHT = 'FlightController/0/NoGPSMaxFlightHeight'
        OMNI_DOWN_AVOIDANCE_DISTANCE = 'FlightController/0/OmniDownAvoidanceDistance'
        OMNI_DOWN_RADAR_DISTANCE = 'FlightController/0/OmniDownRadarDistance'
        OMNI_HORIZONTAL_AVOIDANCE_DISTANCE = 'FlightController/0/OmniHorizontalAvoidanceDistance'
        OMNI_HORIZONTAL_AVOIDANCE_ENABLED = 'FlightController/0/OmniHorizontalAvoidanceEnable'
        OMNI_HORIZONTAL_RADAR_DISTANCE = 'FlightController/0/OmniHorizontalRadarDistance'
        OMNI_PERCEPTION_AVOIDANCE_STATE = 'FlightController/0/OmniPerceptionAvoidanceState'
        OMNI_PERCEPTION_RADAR_BIRD_VIEW_DISTANCE = 'FlightController/0/OmniPerceptionRadarBirdViewDistance'
        OMNI_PERCEPTION_RADAR_DOWN_DISTANCE = 'FlightController/0/OmniPerceptionRadarDownDistance'
        OMNI_PERCEPTION_RADAR_FULL_DISTANCE = 'FlightController/0/OmniPerceptionRadarFullDistance'
        OMNI_PERCEPTION_RADAR_UP_DISTANCE = 'FlightController/0/OmniPerceptionRadarUpDistance'
        OMNI_UP_AVOIDANCE_DISTANCE = 'FlightController/0/OmniUpAvoidanceDistance'
        OMNI_UP_RADAR_DISTANCE = 'FlightController/0/OmniUpRadarDistance'
        OMNI_VERTICAL_AVOIDANCE_ENABLED = 'FlightController/0/OmniVerticalAvoidanceEnable'
        ORIENTATION_MODE = 'FlightController/0/IocMode'
        OUT_OF_BOTH_CONTROL_GIMBALS_REASON = 'FlightController/0/outOfBothControlGimbalsReason'
        POWER_SUPPLY_PORT_ENABLED = 'FlightController/0/PowerSupplyPortEnabled'
        PRECISION_LANDING_ENABLED = 'FlightController/0/PreciseLandingEnabled'
        PRECISION_TAKE_OFF = 'FlightController/0/PrecisionTakeOff'
        QUICK_SPIN_ENABLED = 'FlightController/0/QuickSpin'
        RC_MODE_CHANNEL = 'FlightController/0/RcModeChannel'
        REDUNDANCY_COMPASS_STATUS = 'FlightController/0/redundnacyCompassStatus'
        REDUNDANCY_IMU_STATUS = 'FlightController/0/redundancyImuStatus'
        REDUNDANCY_SENSOR_USED_STATE = 'FlightController/0/RedundancySensorUsedState'
        REMAINING_FLIGHT_TIME = 'FlightController/0/RemainingFlightTime'
        RESET_GRAVITY_CENTER_CALIBRATION = 'FlightController/0/reset_gravity_center_calibration'
        RESET_MOTOR = 'FlightController/0/ResetMotor'
        RESET_USER_ACCOUNT = 'FlightController/0/resetUserAccount'
        RETRACT_LANDING_GEAR = 'FlightController/0/RetractLandingGear'
        RTH_OBSTACLE_AVOIDANCE_ENABLED = 'FlightController/0/RTHObstacleAvoidanceEnabled'
        RTH_REMOTE_OBSTACLE_AVOIDANCE_ENABLED = 'FlightController/0/RTHRemoteObstacleAvoidanceEnabled'
        RTK_ACTIVATE = 'FlightController/0/RtkActivate'
        RTK_BASE_STATION_CONNECTION_STATE = 'FlightController/0/RTKBaseStationConnectionState'
        RTK_BASE_STATION_LIST = 'FlightController/0/RTKBaseStationList'
        RTK_BASE_STATION_LOCATION_STATE = 'FlightController/0/RTKBaseStationLocationState'
        RTK_CONNECTED_WITH_BASE_STATION = 'FlightController/0/RTKConnectedWithBaseStation'
        RTK_CONNECT_TYPE = 'FlightController/0/RtkConnectType'
        RTK_DEVICE_NAME = 'FlightController/0/RtkDeviceName'
        RTK_DEVICE_PASSWORD = 'FlightController/0/RtkDevicePassword'
        RTK_ENABLED = 'FlightController/0/RTKEnabled'
        RTK_FUSION_HAS_SET_TAKE_OFF_ALTITUDE = 'FlightController/0/RTKFusionHasSetTakeOffAltitude'
        RTK_FUSION_HOME_LOCATION_DATA_SOURCE = 'FlightController/0/RTKFusionHomeLocationDataSource'
        RTK_FUSION_MOBILE_HEADING = 'FlightController/0/RTKFusionHeading'
        RTK_FUSION_MOBILE_LOCATION = 'FlightController/0/RTKFusionLocation'
        RTK_FUSION_TAKE_OFF_ALTITUDE = 'FlightController/0/RTKFusionTakeOffAltitude'
        RTK_HEADING_SOLUTION = 'FlightController/0/RTKDirectEnabled'
        RTK_POSITIONING_SOLUTION = 'FlightController/0/RTKStatus'
        RTK_REFERENCE_STATION_SOURCE = 'FlightController/0/RtkReferenceStationSource'
        RTK_SERIAL_NUMBER = 'FlightController/0/SerialNumber'
        RTK_STATE = 'FlightController/0/RTKState'
        SATELLITE_COUNT = 'FlightController/0/SatelliteCount'
        SEND_DATA_TO_ON_BOARD_SDK_DEVICE = 'FlightController/0/SendDataToOnboardSDKDevice'
        SEND_VIRTUAL_STICK_FLIGHT_CONTROL_DATA = 'FlightController/0/SendVirtualStickFlightControlData'
        SERIAL_NUMBER = 'FlightController/0/SerialNumber'
        SERIOUS_LOW_BATTERY_WARNING_THRESHOLD = 'FlightController/0/SeriousLowBatteryWarningThreshold'
        SET_DATA_UPGRADE_SELF = 'FlightController/0/SetUpgradeSelf'
        SET_MULTI_TRACKING_ENABLED_WITH_VIDEO_SOURCE = 'FlightController/0/SetMultiTrackingEnabledWithVideoSource'
        SET_UP_USER = 'FlightController/0/SetUpUser'
        SIMULATOR_STATE = 'FlightController/0/SimulatorState'
        SIMULATOR_WIND_DATA = 'FlightController/0/SimulatorWindData'
        SINGLE_VISION_SENSOR_ENABLED = 'FlightController/0/SingleVisionSensorEnabled'
        SMART_RETURN_TO_HOME_ENABLED = 'FlightController/0/SmartReturnToHomeEnabled'
        SMART_TRACK_SET_CAMERA_FOCAL = 'FlightController/0/SmartTrackSetCameraFocal'
        START_GO_HOME = 'FlightController/0/GoHome'
        START_GRAVITY_CENTER_CALIBRATION = 'FlightController/0/start_gravity_center_calibration'
        START_IMU_CALIBRATION = 'FlightController/0/StartIMUCalibration'
        START_IMU_CALIBRATION_WITH_ID = 'FlightController/0/StartIMUCalibrationWithID'
        START_LANDING = 'FlightController/0/AutoLanding'
        START_SEARCH_BASE_STATION = 'FlightController/0/StartSearchBaseStation'
        START_SIMULATOR = 'FlightController/0/StartSimulator'
        STOP_GRAVITY_CENTER_CALIBRATION = 'FlightController/0/stop_gravity_center_calibration'
        STOP_SEARCH_BASE_STATION = 'FlightController/0/StopSearchBaseStation'
        STOP_SIMULATOR = 'FlightController/0/StopSimulator'
        SUBCOMPONENT_IMU_KEY = 'FlightController/0/Imu'
        SUBSCRIBE_PACK = 'FlightController/0/SubscribePack'
        TAKEOFF_LOCATION_ALTITUDE = 'FlightController/0/TakeoffLocationAltitude'
        TAKE_OFF = 'FlightController/0/TakeOff'
        TAP_FLY_MODE = 'FlightController/0/TapFlyMode'
        TEMP_MOTOR_LOCKED = 'FlightController/0/TempMotorLocked'
        TERRAIN_FOLLOW_MODE_ENABLED = 'FlightController/0/TerrainFollowModeEnabled'
        TIME_NEEDED_TO_GO_HOME = 'FlightController/0/TimeNeededToGoHome'
        TIME_NEEDED_TO_LAND_FROM_CURRENT_HEIGHT = 'FlightController/0/TimeNeededToLandFromCurrentHeight'
        TOP_AUXILIARY_LIGHT_MODE = 'FlightController/0/TopAuxiliaryLightMode'
        TRIPOD_MODE_ENABLED = 'FlightController/0/TripodModeEnabled'
        TURN_OFF_MOTORS = 'FlightController/0/TurnOffMotors'
        TURN_ON_MOTORS = 'FlightController/0/TurnOnMotors'
        ULTRASONIC_ERROR = 'FlightController/0/UltrasonicError'
        ULTRASONIC_HEIGHT_IN_METERS = 'FlightController/0/UltrasonicHeightInMeters'
        UNSUBSCRIBE_PACK = 'FlightController/0/UnsubscribePack'
        UPGRADE_VOICE_OPEN = 'FlightController/0/upgrade_voice_open'
        UPWARDS_AVOIDANCE_ENABLED = 'FlightController/0/RoofAvoidance'
        URGENT_STOP_MOTOR_MODE = 'FlightController/0/UrgentStopMotorMode'
        VELOCITY_X = 'FlightController/0/VelocityX'
        VELOCITY_Y = 'FlightController/0/VelocityY'
        VELOCITY_Z = 'FlightController/0/VelocityZ'
        VIRTUAL_STICK_CONTROL_MODE_ENABLED = 'FlightController/0/VirtualStickControlModeEnabled'
        VISION_ASSISTED_POSITIONING_ENABLED = 'FlightController/0/VisionPositioningEnabled'
        VISION_DETECTION_STATE = 'FlightController/0/VisionDetectionState'
        VISION_SYSTEM_WARNING = 'FlightController/0/VisionSystemWarning'
        WAYPOINT_GIMBAL = 'FlightController/0/WayPointGimbal'
        WAYPOINT_MISSION_INTERRUPTION = 'FlightController/0/WaypointMissionInterruption'
        WAYPOINT_PROTOCOL_VERSION = 'FlightController/0/WaypointProtocolVersion'
        WIND_DIRECTION = 'FlightController/0/WindDirection'
        WIND_SPEED = 'FlightController/0/WindSpeed'
        DEBUG1 = 'FlightController/0/FlightControllerConfigSportThrottleExperienceMidPoint'
        DEBUG2 = 'FlightController/0/ConfigSportThrottleExperienceMidPoint'
        DEBUG3 = 'FlightControllerConfigSportThrottleExperienceMidPoint'
        DEBUG4 = 'FlightController/0/IsInPreciseLanding'


    class Diagnostics(Enum):
        SYSTEM_STATUS = 'Diagnostics/0/SystemStatus'

    class Camera(Enum):
        ACTIVATE_SSD_VIDEO_LICENSE = 'Camera/0/ActivateSSDVideoLicense'
        AE_LOCK = 'Camera/0/AELock'
        ANTI_FLICKER_FREQUENCY = 'Camera/0/AntiFlickerFrequency'
        ANTI_FLICKER_RANGE = 'Camera/0/CameraAntiFlickerRange'
        APERTURE = 'Camera/0/Aperture'
        APERTURE_RANGE = 'Camera/0/ApertureRange'
        AUDIO_GAIN = 'Camera/0/AudioGain'
        AUDIO_RECORDING_ENABLED = 'Camera/0/AudioRecordingEnabled'
        AUTO_AE_UNLOCK_ENABLED = 'Camera/0/AutoAEUnlockEnabled'
        AUTO_LOCK_GIMBAL_ENABLED = 'Camera/0/AutoLockGimbalEnabled'
        CAMERA_COLOR = 'Camera/0/CameraColor'
        CAMERA_COLOR_RANGE = 'Camera/0/cameraColorRange'
        CAMERA_MF_DEMARCATE_RESULT = 'Camera/0/CameraMFDemarcateResult'
        CAMERA_MF_DEMARCATE_STATE = 'Camera/0/CameraMFDemarcateState'
        CAMERA_PEAK_THRESHOLD = 'Camera/0/CameraPeakThreshold'
        CAMERA_START_MF_DEMARCATE = 'Camera/0/CameraStartMFDemarcate'
        CAMERA_STOP_MF_DEMARCATE = 'Camera/0/CameraStopMFDemarcate'
        CAMERA_STORAGE_LOCATION = 'Camera/0/CameraStorageLocation'
        CAMERA_TARGET_FOCAL_LENGTH = 'Camera/0/CameraTargetFocalLength'
        CAMERA_TYPE = 'Camera/0/CameraType'
        CAMERA_VIDEO_STREAM_SOURCE = 'Camera/0/CameraVideoStreamSource'
        CAMERA_VIDEO_STREAM_SOURCE_RANGE = 'Camera/0/CameraVideoStreamSourceRange'
        CAPTURE_CAMERA_STREAM_SETTINGS = 'Camera/0/CaptureCameraStreamSettings'
        CLEAR_LOG_EXPORT = 'Camera/0/ClearLogExport'
        COLOR_WAVEFORM_DISPLAY_STATE = 'Camera/0/ColorWaveformDisplayState'
        COLOR_WAVEFORM_ENABLED = 'Camera/0/ColorWaveformEnabled'
        CONTRAST = 'Camera/0/Contrast'
        CURRENT_PANORAMA_PHOTO_COUNT = 'Camera/0/CurrentPanoramaPhotoCount'
        CURRENT_THERMAL_GAIN_MODE_TEMPERATURE_RANGE = 'Camera/0/CurrentThermalGainModeTemperatureRange'
        CURRENT_VIDEO_RECORDING_TIME_IN_SECONDS = 'Camera/0/CurrentVideoRecordingTimeInSeconds'
        CUSTOM_INFORMATION = 'Camera/0/CUSTOM_INFORMATION'
        DEFOG_ENABLED = 'Camera/0/DefogEnabled'
        DEMARCATE_VALUE = 'Camera/0/DemarcateValue'
        DEWARPING_ENABLED = 'Camera/0/DewarpingEnabled'
        DIGITAL_ZOOM_FACTOR = 'Camera/0/DigitalZoomFactor'
        DISPLAY_MODE = 'Camera/0/DisplayModeForXT2'
        DISPLAY_MODE_RANGE = 'Camera/0/DisplayModeRange'
        DISPLAY_NAME = 'Camera/0/DisplayName'
        DUAL_FEED_HORIZONTAL_ALIGNMENT_OFFSET = 'Camera/0/DualFeedHorizontalAlignmentOffset'
        DUAL_FEED_HORIZONTAL_ALIGNMENT_OFFSET_RANGE = 'Camera/0/DualFeedHorizontalAlignmentOffsetRange'
        DUAL_FEED_VERTICAL_ALIGNMENT_OFFSET = 'Camera/0/DualFeedVerticalAlignmentOffset'
        DUAL_FEED_VERTICAL_ALIGNMENT_OFFSET_RANGE = 'Camera/0/DualFeedVerticalAlignmentOffsetRange'
        EI_COLOR = 'Camera/0/EIColor'
        EI_VALUE = 'Camera/0/EIValue'
        EI_VALUE_RANGE = 'Camera/0/EIRange'
        ENTER_PLAYBACK = 'Camera/0/enterPlayback'
        EXIT_PLAYBACK = 'Camera/0/exitPlayback'
        EXIT_SENSOR_CLEANING_MODE = 'Camera/0/exitSensorDedustingMode'
        EXPOSURE_COMPENSATION = 'Camera/0/ExposureCompensation'
        EXPOSURE_COMPENSATION_RANGE = 'Camera/0/ExposureCompensationRange'
        EXPOSURE_MODE = 'Camera/0/ExposureMode'
        EXPOSURE_MODE_RANGE = 'Camera/0/ExposureModeRange'
        EXPOSURE_SENSITIVITY_MODE = 'Camera/0/ExposureSensitivityMode'
        EXPOSURE_SETTINGS = 'Camera/0/ExposureSettings'
        EXPOSURE_STATE = 'Camera/0/ExposureState'
        FAST_PLAYBACK_SETTINGS = 'Camera/0/FastPlayBackSettings'
        FILE_INDEX_MODE = 'Camera/0/FileIndexMode'
        FIRMWARE_VERSION = 'Camera/0/FirmwareVersion'
        FLAT_CAMERA_MODE = 'Camera/0/FlatCameraMode'
        FLAT_CAMERA_MODE_CHILD_RANGE = 'Camera/0/FlatCameraModeChildRange'
        FLAT_CAMERA_MODE_RANGE = 'Camera/0/FlatCameraModeRange'
        FLAT_PHOTO_MODE_RANGE = 'Camera/0/FlatPhotoModeRange'
        FOCUS_ASSISTANT_SETTINGS = 'Camera/0/FocusAssistantSettings'
        FOCUS_MODE = 'Camera/0/FocusMode'
        FOCUS_RING_VALUE = 'Camera/0/FocusRingValue'
        FOCUS_RING_VALUE_UPPER_BOUND = 'Camera/0/FocusRingValueUpperBound'
        FOCUS_STATUS = 'Camera/0/FocusStatus'
        FOCUS_TARGET = 'Camera/0/FocusTarget'
        FORMAT_INTERNAL_STORAGE = 'Camera/0/FormatInternalStorage'
        FORMAT_SD_CARD = 'Camera/0/FormatSDCard'
        FORMAT_SSD = 'Camera/0/FormatSSD'
        HARDWARE_VERSION = 'Camera/0/HardwareVersion'
        HAS_ERROR = 'Camera/0/HasError'
        HD_LIVE_VIEW_ENABLED = 'Camera/0/HDLiveViewEnabled'
        HISTOGRAM_ENABLED = 'Camera/0/HistogramEnabled'
        HISTOGRAM_LIGHT_VALUES = 'Camera/0/HistogramLightValues'
        HYBRID_ZOOM_FOCAL_LENGTH = 'Camera/0/HybridZoomFocalLength'
        HYBRID_ZOOM_SPEC = 'Camera/0/HybridZoomSpec'
        HYPERLAPSE_ORIGINAL_IMAGES_FORMAT_RANGE = 'Camera/0/HyperlapseOriginalImagesFormatRange'
        HYPERLAPSE_ORIGINAL_PHOTO_SETTINGS = 'Camera/0/HyperlapseOriginalPhotoSettings'
        INFRARED_THERMAL_CAMERA_SENSOR_BURNING_PROTECTION_ENABLED = 'Camera/0/InfraredThermalCameraSensorBurningProtectionEnabled'
        INFRARED_THERMAL_CAMERA_SHUTTER_ENABLED = 'Camera/0/InfraredThermalCameraShutterEnabled'
        INIT_SENSOR_CLEANING_MODE = 'Camera/0/enterSensorDedustingMode'
        INNERSTORAGE_AVAILABLE_CAPTURE_COUNT = 'Camera/0/InnerStorageAvailableCaptureCount'
        INNERSTORAGE_AVAILABLE_RECORDING_TIME_IN_SECONDS = 'Camera/0/InnerStorageAvailableRecordingTimeInSeconds'
        INNERSTORAGE_HAS_ERROR = 'Camera/0/InnerStorageHasError'
        INNERSTORAGE_IS_BUSY = 'Camera/0/InnerStorageIsBusy'
        INNERSTORAGE_IS_FORMATTED = 'Camera/0/InnerStorageIsFormatted'
        INNERSTORAGE_IS_FORMATTING = 'Camera/0/InnerStorageIsFormatting'
        INNERSTORAGE_IS_FULL = 'Camera/0/InnerStorageIsFull'
        INNERSTORAGE_IS_INITIALIZING = 'Camera/0/InnerStorageIsInitializing'
        INNERSTORAGE_IS_INSERTED = 'Camera/0/InnerStorageInsert'
        INNERSTORAGE_IS_INVALID_FORMAT = 'Camera/0/InnerStorageIsInvalidFormat'
        INNERSTORAGE_IS_READ_ONLY = 'Camera/0/InnerStorageIsReadOnly'
        INNERSTORAGE_IS_SLOW = 'Camera/0/InnerStorageIsSlow'
        INNERSTORAGE_IS_VERIFIED = 'Camera/0/InnerStorageIsVerified'
        INNERSTORAGE_REMAINING_SPACE_IN_MB = 'Camera/0/InnerStorageRemainingSpaceInMB'
        INNERSTORAGE_STATE = 'Camera/0/InnerStorageState'
        INNERSTORAGE_TOTAL_SPACE_IN_MB = 'Camera/0/InnerStorageTotalSpaceInMB'
        INTERVAL_SHOOT_COUNTDOWN = 'Camera/0/IntervalShootCountdown'
        IRC_ENABLE = 'Camera/0/IRCEnable'
        ISO = 'Camera/0/ISO'
        ISO_RANGE = 'Camera/0/ISORange'
        IS_ADJUSTABLE_APERTURE_SUPPORTED = 'Camera/0/IsAdjustableApertureSupported'
        IS_ADJUSTABLE_FOCAL_POINT_SUPPORTED = 'Camera/0/IsAdjustableFocalPointSupported'
        IS_AFC_SUPPORTED = 'Camera/0/isContinuousAutoFocusSupported'
        IS_AUDIO_RECORDING_SUPPORTED = 'Camera/0/IsAudioRecordingSupported'
        IS_CAPTURE_IN_VIDEO_SUPPORTED = 'Camera/0/isCaptureInVideoSupported'
        IS_COLOR_WAVEFORM_SUPPORTED = 'Camera/0/IsColorWaveformSupported'
        IS_DEWARPING_SUPPORTED = 'Camera/0/isDewarpingSupported'
        IS_DIGITAL_ZOOM_SUPPORTED = 'Camera/0/IsDigitalZoomSupported'
        IS_EI_MODE_SUPPORTED = 'Camera/0/isEIModeSupported'
        IS_FLAT_CAMERA_MODE_SUPPORTED = 'Camera/0/isFlatCameraModeSupported'
        IS_HYBRID_ZOOM_SUPPORTED = 'Camera/0/IsHybridZoomSupported'
        IS_INTERCHANGEABLE_LENS_SUPPORTED = 'Camera/0/IsInterchangeableLensSupported'
        IS_INTERNAL_STORAGE_SUPPORTED = 'Camera/0/isInternalStorageSupported'
        IS_IN_PLAYBACK_MODE = 'Camera/0/isInPlaybackMode'
        IS_LOG_EXPORTING = 'Camera/0/IsLogExporting'
        IS_MECHANICAL_SHUTTER_SUPPORTED = 'Camera/0/isMechanicalShutterSupported'
        IS_MEDIA_DOWNLOAD_MODE_SUPPORTED = 'Camera/0/IsMediaDownloadModeSupported'
        IS_METERING_MODE_SUPPORTED = 'Camera/0/IsMeteringModeSupported'
        IS_MULTI_LENS_CAMERA_SUPPORTED = 'Camera/0/isMultiLensCameraSupported'
        IS_ND_FILTER_MODE_SUPPORTED = 'Camera/0/isNDFilterModeSupported'
        IS_OPTICAL_ZOOM_SUPPORTED = 'Camera/0/IsOpticalZoomSupported'
        IS_OVERHEATING = 'Camera/0/isOverheating'
        IS_PHOTO_QUICK_VIEW_SUPPORTED = 'Camera/0/IsPhotoQuickViewSupported'
        IS_PLAYBACK_SUPPORTED = 'Camera/0/isPlaybackSupported'
        IS_PROCESSING_PANORAMA_PHOTO = 'Camera/0/IsProcessingPanoramaPhoto'
        IS_RECORDING = 'Camera/0/IsRecording'
        IS_SENSOR_CLEANING_SUPPORTED = 'Camera/0/isSensorCleaningSupported'
        IS_SHOOTING_BURST_PHOTO = 'Camera/0/IsShootingBurstPhoto'
        IS_SHOOTING_INTERVAL_PHOTO = 'Camera/0/IsShootingIntervalPhoto'
        IS_SHOOTING_PANORAMA_PHOTO = 'Camera/0/IsShootingPanoramaPhoto'
        IS_SHOOTING_PHOTO = 'Camera/0/IsShootingPhoto'
        IS_SHOOTING_PHOTO_ENABLED = 'Camera/0/IsShootPhotoEnabled'
        IS_SHOOTING_RAW_BURST_PHOTO = 'Camera/0/IsShootingRawBurstPhoto'
        IS_SHOOTING_SHALLOW_FOCUS_PHOTO = 'Camera/0/IsShootingShallowFocusPhoto'
        IS_SHOOTING_SINGLE_PHOTO = 'Camera/0/IsShootingSinglePhoto'
        IS_SHOOTING_SINGLE_PHOTO_IN_RAW_FORMAT = 'Camera/0/IsShootingSinglePhotoInRAWFormat'
        IS_SHOOTING_SUPER_RESOLUTION_PHOTO = 'Camera/0/IsShootingSuperResolutionPhoto'
        IS_SSD_SUPPORTED = 'Camera/0/IsSSDSupported'
        IS_STORING_PHOTO = 'Camera/0/IsStoringPhoto'
        IS_SUPER_RESOLUTION_SUPPORTED = 'Camera/0/isSuperResolutionSupported'
        IS_TAP_ZOOM_SUPPORTED = 'Camera/0/isTapZoomSupported'
        IS_THERMAL_CAMERA = 'Camera/0/IsThermalCamera'
        IS_THERMAL_LENS = 'Camera/0/isThermalLens'
        IS_TIME_LAPSE_SUPPORTED = 'Camera/0/IsTimeLapseSupported'
        IS_VIDEO_PLAYBACK_SUPPORTED = 'Camera/0/isVideoPlaybackSupported'
        LASER_ENABLED = 'Camera/0/LaserEnabled'
        LASER_MEASURE_INFORMATION = 'Camera/0/LaserMeasureInformation'
        LEDS_AUTO_TURN_OFF_ENABLED_SETTINGS = 'Camera/0/LEDsAutoTurnOffEnabledSettings'
        LED_AUTO_TURN_OFF_ENABLED = 'Camera/0/LEDAutoTurnOffEnabled'
        LENS_INFORMATION = 'Camera/0/LensInformation'
        LENS_IS_AF_SWITCH_ON = 'Camera/0/LensIsAFSwitchOn'
        LENS_IS_FOCUS_ASSISTANT_WORKING = 'Camera/0/LensIsFocusAssistantWorking'
        LENS_IS_INSTALLED = 'Camera/0/LensIsInstalled'
        LOAD_SETTINGS_FROM_PROFILE = 'Camera/0/LoadSettingsFromProfile'
        LOG_EXPORT_STATE = 'Camera/0/LogExportState'
        MECHANICAL_SHUTTER_ENABLED = 'Camera/0/MechanicalShutterEnabled'
        METERING_MODE = 'Camera/0/MeteringMode'
        MODE = 'Camera/0/Mode'
        MODE_RANGE = 'Camera/0/CameraModeRange'
        MSX_LEVEL = 'Camera/0/BlendingLevel'
        MULTI_SPECTRAL_EXPOSURE_COMPENSATION_RANGE = 'Camera/0/MultispectralExposureCompensationRange'
        MULTI_SPECTRAL_SHUTTER_SPEED_RANGE = 'Camera/0/MultispectralShutterSpeedRange'
        NDFILTER_MODE = 'Camera/0/NDFilterMode'
        OPTICAL_ZOOM_FOCAL_LENGTH = 'Camera/0/OpticalZoomFocalLength'
        OPTICAL_ZOOM_SCALE = 'Camera/0/OpticalZoomScale'
        OPTICAL_ZOOM_SPEC = 'Camera/0/OpticalZoomSpec'
        ORIENTATION = 'Camera/0/Orientation'
        ORIENTATION_RANGE = 'Camera/0/CameraOrientationRange'
        PANORAMA_CAPTURE_RESULT = 'Camera/0/PanoramaCaptureResult'
        PANORAMA_PROGRESS_IN_PERCENT = 'Camera/0/PanoramaProgressInPercent'
        PANO_ORIGINAL_IMAGES_FORMAT_RANGE = 'Camera/0/PanoOriginalImagesFormatRange'
        PANO_ORIGINAL_PHOTO_SETTINGS = 'Camera/0/PanoOriginalPhotoSettings'
        PHOTO_AEB_COUNT = 'Camera/0/PhotoAEBCount'
        PHOTO_ASPECT_RATIO = 'Camera/0/PhotoAspectRatio'
        PHOTO_ASPECT_RATIO_RANGE = 'Camera/0/PhotoAspectRatioRange'
        PHOTO_BURST_COUNT = 'Camera/0/PhotoBurstCount'
        PHOTO_FILE_FORMAT = 'Camera/0/PhotoFileFormat'
        PHOTO_FILE_FORMAT_RANGE = 'Camera/0/PhotoFileFormatRange'
        PHOTO_PANORAMA_MODE = 'Camera/0/PhotoPanoramaMode'
        PHOTO_QUICK_VIEW_DURATION = 'Camera/0/PhotoQuickViewDuration'
        PHOTO_RAW_BURST_COUNT = 'Camera/0/PhotoRAWBurstCount'
        PHOTO_TIME_INTERVAL_SETTINGS = 'Camera/0/PhotoTimeIntervalSettings'
        PHOTO_TIME_LAPSE_SETTINGS = 'Camera/0/PhotoTimeLapseSettings'
        PICTURE_STYLE_PRESET = 'Camera/0/PictureStylePreset'
        PIP_POSITION = 'Camera/0/PipModeForXT2'
        RAW_PHOTO_BURST_COUNT = 'Camera/0/RAWPhotoBurstCount'
        RC_WHEEL_MODE = 'Camera/0/RcWheelMode'
        RECOMMENDED_EI_VALUE = 'Camera/0/RecommendedEI'
        RECORDING_STATE = 'Camera/0/RecordingState'
        RECORD_CAMERA_STREAM_SETTINGS = 'Camera/0/RecordCameraStreamSettings'
        RESOLUTION_FRAME_RATE = 'Camera/0/ResolutionFrameRate'
        RESTORE_FACTORY_SETTINGS = 'Camera/0/restoreFactorySettings'
        SATURATION = 'Camera/0/Saturation'
        SAVE_SETTINGS_TO_PROFILE = 'Camera/0/SaveSettingsToProfile'
        SDCARD_AVAILABLE_CAPTURE_COUNT = 'Camera/0/SDCardAvailableCaptureCount'
        SDCARD_AVAILABLE_RECORDING_TIME_IN_SECONDS = 'Camera/0/SDCardAvailableRecordingTimeInSeconds'
        SDCARD_HAS_ERROR = 'Camera/0/SDCardHasError'
        SDCARD_IS_BUSY = 'Camera/0/SDCardIsBusy'
        SDCARD_IS_CONNECTED_TO_PC = 'Camera/0/SDCardIsConnectedToPC'
        SDCARD_IS_FORMATTED = 'Camera/0/SDCardIsFormatted'
        SDCARD_IS_FORMATTING = 'Camera/0/SDCardIsFormatting'
        SDCARD_IS_FULL = 'Camera/0/SDCardIsFull'
        SDCARD_IS_INITIALIZING = 'Camera/0/SDCardIsInitializing'
        SDCARD_IS_INSERTED = 'Camera/0/SDCardIsInserted'
        SDCARD_IS_INVALID_FORMAT = 'Camera/0/SDCardIsInvalidFormat'
        SDCARD_IS_READ_ONLY = 'Camera/0/SDCardIsReadOnly'
        SDCARD_IS_REPAIRING_FILES = 'Camera/0/SDCardIsRepairingFiles'
        SDCARD_IS_SLOW = 'Camera/0/SDCardIsSlow'
        SDCARD_IS_VERIFIED = 'Camera/0/SDCardIsVerified'
        SDCARD_IS_WRITE_SLOW = 'Camera/0/SDCardIsWriteSlow'
        SDCARD_NEEDS_FORMATTING = 'Camera/0/SDCardNeedsFormatting'
        SDCARD_REMAINING_SPACE_IN_MB = 'Camera/0/SDCardRemainingSpaceInMB'
        SDCARD_STATE = 'Camera/0/SDCardState'
        SDCARD_TOTAL_SPACE_IN_MB = 'Camera/0/SDCardTotalSpaceInMB'
        SENSOR_CLEANING_STATE = 'Camera/0/SensorCleaningState'
        SERIAL_NUMBER = 'Camera/0/SerialNumber'
        SHARPNESS = 'Camera/0/Sharpness'
        SHOOT_PHOTO_MODE = 'Camera/0/ShootPhotoMode'
        SHOOT_PHOTO_MODE_CHILD_RANGE = 'Camera/0/ShootPhotoChildRange'
        SHOOT_PHOTO_MODE_RANGE = 'Camera/0/ShootPhotoModeRange'
        SHUTTER_SPEED = 'Camera/0/ShutterSpeed'
        SHUTTER_SPEED_RANGE = 'Camera/0/ShutterSpeedRange'
        SPOT_METERING_TARGET = 'Camera/0/SpotMeteringTarget'
        SSD_AVAILABLE_RECORDING_TIME_IN_SECONDS = 'Camera/0/SSDAvailableRecordingTimeInSeconds'
        SSD_CLIP_FILE_NAME = 'Camera/0/SSDClipFileName'
        SSD_COLOR = 'Camera/0/SSDColor'
        SSD_COLOR_RANGE = 'Camera/0/SSDVideoLookRange'
        SSD_IS_CONNECTED = 'Camera/0/SSDIsConnected'
        SSD_LEGACY_COLOR = 'Camera/0/SSDLegacyColor'
        SSD_OPERATION_STATE = 'Camera/0/SSDOperationState'
        SSD_REMAINING_SPACE_IN_MB = 'Camera/0/SSDRemainingSpaceInMB'
        SSD_TOTAL_SPACE = 'Camera/0/SSDTotalSpace'
        SSD_VIDEO_LICENSES = 'Camera/0/SSDVideoLicenses'
        SSD_VIDEO_RECORDING_ENABLED = 'Camera/0/SSDVideoRecordingEnabled'
        SSD_VIDEO_RESOLUTION_AND_FRAME_RATE = 'Camera/0/SSDVideoResolutionAndFrameRate'
        SSD_VIDEO_RESOLUTION_FRAME_RATE_RANGE = 'Camera/0/SSDVideoResolutionFrameRateRange'
        SSD_VIDEO_RESOLUTION_RANGE = 'Camera/0/SSDVideoResolutionRange'
        START_CONTINUOUS_OPTICAL_ZOOM = 'Camera/0/StartContinuousOpticalZoom'
        START_LOG_EXPORT = 'Camera/0/StartLogExport'
        START_RECORD_VIDEO = 'Camera/0/StartRecordVideo'
        START_RECORD_VIDEO_IN_CACHE = 'Camera/0/StartRecordVideoInCache'
        START_SENSOR_CLEANING = 'Camera/0/startSensorDedusting'
        START_SHOOT_PHOTO = 'Camera/0/StartShootPhoto'
        STOP_CONTINUOUS_OPTICAL_ZOOM = 'Camera/0/StopContinuousOpticalZoom'
        STOP_LOG_EXPORT = 'Camera/0/StopLogExport'
        STOP_RECORD_VIDEO = 'Camera/0/StopRecordVideo'
        STOP_RECORD_VIDEO_IN_CACHE = 'Camera/0/StopRecordVideoInCache'
        STOP_SHOOT_PHOTO = 'Camera/0/StopShootPhoto'
        STORAGE_STATE = 'Camera/0/StorageState'
        SUPER_RESOLUTION_CAPTURE_AREA = 'Camera/0/SuperResolutionCaptureArea'
        SUPER_RESOLUTION_STATE = 'Camera/0/SuperResolutionState'
        TAP_ZOOM_AT_TARGET = 'Camera/0/TapZoomAtTarget'
        TAP_ZOOM_ENABLED = 'Camera/0/TapZoomEnabled'
        TAP_ZOOM_MULTIPLIER = 'Camera/0/TapZoomMultiplier'
        TAP_ZOOM_STATE = 'Camera/0/TapZoomState'
        TEMPERATURE_UNIT = 'Camera/0/temperatureUnitInSpot'
        TEMP_ALARM = 'Camera/0/TempAlarm'
        THERMAL_ACE = 'Camera/0/ThermalACE'
        THERMAL_AREA_TEMPERATURE_AGGREGATIONS = 'Camera/0/ThermalAreaTemperatureAggregations'
        THERMAL_ATMOSPHERIC_TEMPERATURE = 'Camera/0/ThermalAtmosphericTemperature'
        THERMAL_ATMOSPHERIC_TRANSMISSION_COEFFICIENT = 'Camera/0/ThermalAtmosphericTransmissionCoefficient'
        THERMAL_BACKGROUND_TEMPERATURE = 'Camera/0/ThermalBackgroundTemperature'
        THERMAL_BRIGHTNESS = 'Camera/0/ThermalBrightness'
        THERMAL_CONTRAST = 'Camera/0/ThermalContrast'
        THERMAL_CUSTOM_EXTERNAL_SCENE_SETTINGS_PROFILE = 'Camera/0/ThermalCustomExternalSceneSettingsProfile'
        THERMAL_DDE = 'Camera/0/ThermalDDE'
        THERMAL_DIGITAL_ZOOM_FACTOR = 'Camera/0/ThermalDigitalZoomFactor'
        THERMAL_FFC_MODE = 'Camera/0/ThermalFFCMode'
        THERMAL_GAIN_MODE = 'Camera/0/ThermalGainMode'
        THERMAL_GAIN_MODE_TEMPERATURE_RANGE = 'Camera/0/ThermalGainModeTemperatureRange'
        THERMAL_GLOBAL_MAX_TEMPERATURE = 'Camera/0/ThermalGlobalMaxTemperature'
        THERMAL_GLOBAL_MIN_TEMPERATURE = 'Camera/0/ThermalGlobalMinTemperature'
        THERMAL_ISOTHERM_ENABLED = 'Camera/0/ThermalIsothermEnabled'
        THERMAL_ISOTHERM_LOWER_VALUE = 'Camera/0/ThermalIsothermLowerValue'
        THERMAL_ISOTHERM_MIDDLE_VALUE = 'Camera/0/ThermalIsothermMiddleValue'
        THERMAL_ISOTHERM_UNIT = 'Camera/0/ThermalIsothermUnit'
        THERMAL_ISOTHERM_UPPER_VALUE = 'Camera/0/ThermalIsothermUpperValue'
        THERMAL_IS_FFC_MODE_SUPPORTED = 'Camera/0/ThermalIsFFCModeSupported'
        THERMAL_MEASUREMENT_MODE = 'Camera/0/ThermalMeasurementMode'
        THERMAL_MEASURING_STATUS = 'Camera/0/ThermalMeasuringStatus'
        THERMAL_METERING_AREA = 'Camera/0/ThermalMeteringArea'
        THERMAL_PALETTE = 'Camera/0/ThermalPalette'
        THERMAL_PALETTE_RANGE = 'Camera/0/ThermalPaletteRange'
        THERMAL_PROFILE = 'Camera/0/ThermalProfile'
        THERMAL_ROI = 'Camera/0/ThermalROI'
        THERMAL_SCENE = 'Camera/0/ThermalScene'
        THERMAL_SCENE_EMISSIVITY = 'Camera/0/ThermalSceneEmissivity'
        THERMAL_SPOT_METERING_TARGET_POINT = 'Camera/0/ThermalSpotMeteringTargetPoint'
        THERMAL_SSO = 'Camera/0/ThermalSSO'
        THERMAL_TEMPERATURE_DATA = 'Camera/0/ThermalTemperatureData'
        THERMAL_WINDOW_REFLECTED_TEMPERATURE = 'Camera/0/ThermalWindowReflectedTemperature'
        THERMAL_WINDOW_REFLECTION = 'Camera/0/ThermalWindowReflection'
        THERMAL_WINDOW_TEMPERATURE = 'Camera/0/ThermalWindowTemperature'
        THERMAL_WINDOW_TRANSMISSION_COEFFICIENT = 'Camera/0/ThermalWindowTransmissionCoefficient'
        TOTAL_PANORAMA_PHOTO_COUNT = 'Camera/0/TotalPanoramaPhotoCount'
        TRIGGER_THERMAL_FFC = 'Camera/0/TriggerThermalFFC'
        TURN_OFF_FAN_WHEN_POSSIBLE = 'Camera/0/TurnOffFanWhenPossible'
        VIDEO_CAPTION_ENABLED = 'Camera/0/VideoCaptionEnabled'
        VIDEO_COMPRESSION_STANDARD_RANGE = 'Camera/0/VideoCompressionStandardRange'
        VIDEO_FILE_COMPRESSION_STANDARD = 'Camera/0/VideoFileCompressionStandard'
        VIDEO_FILE_FORMAT = 'Camera/0/VideoFileFormat'
        VIDEO_FILE_FORMAT_RANGE = 'Camera/0/VideoFileFormatRange'
        VIDEO_RESOLUTION_FRAME_RATE_RANGE = 'Camera/0/VideoResolutionFrameRateRange'
        VIDEO_STANDARD = 'Camera/0/VideoStandard'
        VIDEO_STANDARD_RANGE = 'Camera/0/VideoStandardRange'
        VISION_STABILIZATION_ENABLED = 'Camera/0/stabilization'
        VISION_STABILIZATION_STATE = 'Camera/0/StabilizationState'
        WATERMARK_DISPLAY_CONTENT_SETTINGS = 'Camera/0/WatermarkDisplayContentSettings'
        WATERMARK_SETTINGS = 'Camera/0/WatermarkSettings'
        WATERMARK_USER_CUSTOM_INFO = 'Camera/0/WatermarkUserCustomInfo'
        WHITE_BALANCE = 'Camera/0/WhiteBalance'
        WHITE_BALANCE_CUSTOM_COLOR_TEMPERATURE_RANGE = 'Camera/0/WhiteBalanceCustomColorTemperatureRange'
        WHITE_BALANCE_PRESENT_RANGE = 'Camera/0/WhiteBalancePresentRange'
        ZOOM_BOX_RELATIVE_FOV = 'Camera/0/ZoomBoxRelative'

    class Gimbal(Enum):
        APPLY_MOTOR_CONTROL_PRESET = 'Gimbal/0/ApplyMotorControlPreset'
        ATTITUDE_IN_DEGREES = 'Gimbal/0/AttitudeInDegrees'
        BALANCE_CHECK_RESULT = 'Gimbal/0/BalanceCheckResult'
        BALANCE_STATE = 'Gimbal/0/BalanceState'
        CALIBRATION_PROGRESS = 'Gimbal/0/CalibrationProgress'
        CAPABILITIES = 'Gimbal/0/Capabilities'
        CONCENTRICITY_CHECK_RESULT = 'Gimbal/0/ConcentricityCheckResult'
        CONNECTION = 'Gimbal/0/Connection'
        CONTROLLER_MODE = 'Gimbal/0/ControllerMode'
        DISPLAY_NAME = 'Gimbal/0/DisplayName'
        FINE_TUNE_PITCH_IN_DEGREES = 'Gimbal/0/FineTunePitchInDegrees'
        FINE_TUNE_ROLL_IN_DEGREES = 'Gimbal/0/FineTuneRollInDegrees'
        FINE_TUNE_YAW_IN_DEGREES = 'Gimbal/0/FineTuneYawInDegrees'
        FIRMWARE_VERSION = 'Gimbal/0/FirmwareVersion'
        GIMBAL_ATTITUDE_SYNCHRONIZATION_ENABLED = 'Gimbal/0/AttitudeSynchronizationEnabled'
        IS_ATTITUDE_RESET = 'Gimbal/0/IsAttitudeReset'
        IS_CALIBRATING = 'Gimbal/0/IsCalibrating'
        IS_CALIBRATION_SUCCESSFUL = 'Gimbal/0/IsCalibrationSuccessful'
        IS_GIMBAL_ON_TOP = 'Gimbal/0/IsGimbalOnTopPosition'
        IS_MOBILE_DEVICE_MOUNTED = 'Gimbal/0/isMobileDeviceMounted'
        IS_MOTOR_OVER_LOADED = 'Gimbal/0/IsMotorOverloaded'
        IS_PITCH_AT_STOP = 'Gimbal/0/IsPitchAtStop'
        IS_ROLL_AT_STOP = 'Gimbal/0/IsRollAtStop'
        IS_STUCK = 'Gimbal/0/IsStuck'
        IS_TESTING_BALANCE = 'Gimbal/0/IsTestingBalance'
        IS_YAW_AT_STOP = 'Gimbal/0/IsYawAtStop'
        MODE = 'Gimbal/0/Mode'
        MOTOR_ENABLED = 'Gimbal/0/MotorEnabled'
        MOVEMENT_SETTINGS_PROFILE = 'Gimbal/0/MovementSettingsProfile'
        PITCH_CONTROLLER_DEADBAND = 'Gimbal/0/PitchControllerDeadband'
        PITCH_CONTROLLER_SMOOTHING_FACTOR = 'Gimbal/0/PitchControllerSmoothingFactor'
        PITCH_CONTROLLER_SPEED_COEFFICIENT = 'Gimbal/0/PitchControllerSpeedCoefficient'
        PITCH_DOWN_ENDPOINT = 'Gimbal/0/PitchDownEndpoint'
        PITCH_FINE_TUNE_IN_DEGREES = 'Gimbal/0/PitchFineTuneInDegrees'
        PITCH_INVERTED_CONTROL_ENABLED = 'Gimbal/0/PitchInvertedControlEnabled'
        PITCH_MOTOR_CONTROL_GYRO_FILTERING_FACTOR = 'Gimbal/0/PitchMotorControlGyroFilteringFactor'
        PITCH_MOTOR_CONTROL_PRE_CONTROL = 'Gimbal/0/PitchMotorControlPreControl'
        PITCH_MOTOR_CONTROL_STIFFNESS = 'Gimbal/0/PitchMotorControlStiffness'
        PITCH_MOTOR_CONTROL_STRENGTH = 'Gimbal/0/PitchMotorControlStrength'
        PITCH_RANGE_EXTENSION_ENABLED = 'Gimbal/0/PitchRangeExtensionEnabled'
        PITCH_SMOOTH_TRACK_ACCELERATION = 'Gimbal/0/PitchSmoothTrackAcceleration'
        PITCH_SMOOTH_TRACK_DEADBAND = 'Gimbal/0/PitchSmoothTrackDeadband'
        PITCH_SMOOTH_TRACK_ENABLED = 'Gimbal/0/PitchSmoothTrackEnabled'
        PITCH_SMOOTH_TRACK_SPEED = 'Gimbal/0/PitchSmoothTrackSpeed'
        PITCH_TEST_RESULT = 'Gimbal/0/PitchTestResult'
        PITCH_UP_ENDPOINT = 'Gimbal/0/PitchUpEndpoint'
        RESET_CONTROL_PARAMETERS = 'Gimbal/0/ResetStiffnessParameter'
        RESET_GIMBAL = 'Gimbal/0/ResetGimbal'
        RESET_GIMBAL_WITH_PARAMETERS = 'Gimbal/0/ResetGimbalWithParameter'
        RESET_GIMBAL_YAW = 'Gimbal/0/ResetGimbalYaw'
        RESTORE_FACTORY_SETTINGS = 'Gimbal/0/RestoreFactorySettings'
        ROLL_FINE_TUNE_IN_DEGREES = 'Gimbal/0/RollFineTuneInDegrees'
        ROLL_MOTOR_CONTROL_GYRO_FILTERING_FACTOR = 'Gimbal/0/RollMotorControlGyroFilteringFactor'
        ROLL_MOTOR_CONTROL_PRE_CONTROL = 'Gimbal/0/RollMotorControlPreControl'
        ROLL_MOTOR_CONTROL_STIFFNESS = 'Gimbal/0/RollMotorControlStiffness'
        ROLL_MOTOR_CONTROL_STRENGTH = 'Gimbal/0/RollMotorControlStrength'
        ROLL_TEST_RESULT = 'Gimbal/0/RollTestResult'
        ROTATE = 'Gimbal/0/Rotate'
        SERIAL_NUMBER = 'Gimbal/0/SerialNumber'
        START_BALANCE_DETECTION = 'Gimbal/0/StartBalanceCheck'
        START_BALANCE_TEST = 'Gimbal/0/StartBalanceTest'
        START_CALIBRATION = 'Gimbal/0/StartCalibration'
        START_CONCENTRICITY_DETECTION = 'Gimbal/0/StartConcentricityCheck'
        START_CONTROL_PARAMETERS_AUTO_TUNING = 'Gimbal/0/StartStiffnessSelfTuning'
        STIFFNESS_SELF_TUNING_RESULT = 'Gimbal/0/StiffnessSelfTuningResult'
        STOP_BALANCE_DETECTION = 'Gimbal/0/StopBalanceCheck'
        STOP_CONCENTRICITY_DETECTION = 'Gimbal/0/StopConcentricityCheck'
        STOP_CONTROL_PARAMETERS_AUTO_TUNING = 'Gimbal/0/StopStiffnessSelfTuning'
        TOGGLE_SELFIE = 'Gimbal/0/ToggleSelfie'
        YAW_ANGLE_WITH_AIRCRAFT_IN_DEGREE = 'Gimbal/0/YawAngleWithAircraftInDegree'
        YAW_CONTROLLER_DEADBAND = 'Gimbal/0/YawControllerDeadband'
        YAW_CONTROLLER_SMOOTHING_FACTOR = 'Gimbal/0/YawControllerSmoothingFactor'
        YAW_CONTROLLER_SPEED_COEFFICIENT = 'Gimbal/0/YawControllerSpeedCoefficient'
        YAW_FINE_TUNE_IN_DEGREES = 'Gimbal/0/YawFineTuneInDegrees'
        YAW_INVERTED_CONTROL_ENABLED = 'Gimbal/0/YawInvertedControlEnabled'
        YAW_LEFT_ENDPOINT = 'Gimbal/0/YawLeftEndpoint'
        YAW_MOTOR_CONTROL_GYRO_FILTERING_FACTOR = 'Gimbal/0/YawMotorControlGyroFilteringFactor'
        YAW_MOTOR_CONTROL_PRE_CONTROL = 'Gimbal/0/YawMotorControlPreControl'
        YAW_MOTOR_CONTROL_STIFFNESS = 'Gimbal/0/YawMotorControlStiffness'
        YAW_MOTOR_CONTROL_STRENGTH = 'Gimbal/0/YawMotorControlStrength'
        YAW_RIGHT_ENDPOINT = 'Gimbal/0/YawRightEndpoint'
        YAW_SIMULTANEOUS_FOLLOW_ENABLED = 'Gimbal/0/YawSynchronousFollowEnabled'
        YAW_SMOOTH_TRACK_ACCELERATION = 'Gimbal/0/YawSmoothTrackAcceleration'
        YAW_SMOOTH_TRACK_DEADBAND = 'Gimbal/0/YawSmoothTrackDeadband'
        YAW_SMOOTH_TRACK_ENABLED = 'Gimbal/0/YawSmoothTrackEnabled'
        YAW_SMOOTH_TRACK_SPEED = 'Gimbal/0/YawSmoothTrackSpeed'

    class RemoteController(Enum):
        ADD_BUTTON_PROFILE_GROUP = 'RemoteController/0/add_user_for_professional_rc'
        AIRCRAFT_CUSTOM_MAPPING = 'RemoteController/0/AircraftCustomMapping'
        AIRCRAFT_MAPPING_STYLE = 'RemoteController/0/AircraftMappingStyle'
        AVAILABLE_MASTERS = 'RemoteController/0/AvailableMasters'
        BUTTON_CONFIG = 'RemoteController/0/full_config_of_professional_rc'
        BUTTON_EVENT_OF_PROFESSIONAL_RC = 'RemoteController/0/buttonEventOfProfessionalRc'
        BUTTON_PROFILE_GROUPS = 'RemoteController/0/get_user_list_of_professional_rc'
        CALIBRATION_STATE = 'RemoteController/0/CalibrationState'
        CHARGE_MOBILE_MODE = 'RemoteController/0/ChargeMobileMode'
        CHARGE_REMAINING = 'RemoteController/0/ChargeRemaining'
        CONNECTED_MASTER_CREDENTIALS = 'RemoteController/0/ConnectedMasterCredentials'
        CONNECT_TO_MASTER = 'RemoteController/0/connectToMaster'
        CONNECT_TO_MASTER_WITH_ID = 'RemoteController/0/connectToMasterWithID'
        CONTROLLING_GIMBAL_INDEX = 'RemoteController/0/controllingGimbalIndex'
        COUNTRY_CODE = 'RemoteController/0/CountryCode'
        CUSTOMIZE_BUTTON = 'RemoteController/0/set_single_config_of_professional_rc'
        CUSTOM_BUTTON_1 = 'RemoteController/0/CustomButton1'
        CUSTOM_BUTTON_2 = 'RemoteController/0/CustomButton2'
        CUSTOM_BUTTON_TAGS = 'RemoteController/0/CustomButtonTags'
        CUSTOM_GIMBAL_MAPPING = 'RemoteController/0/CustomGimbalMapping'
        DISPLAY_NAME = 'RemoteController/0/DisplayName'
        FETCH_CUSTOMIZED_ACTION_OF_BUTTON = 'RemoteController/0/get_single_config_of_professional_rc'
        FIRMWARE_VERSION = 'RemoteController/0/FirmwareVersion'
        FIVE_D_BUTTON = 'RemoteController/0/FiveDButton'
        FLIGHT_MODE_SWITCH_POSITION = 'RemoteController/0/FlightModeSwitchPosition'
        FOCUS_CONTROLLER_CONTROL_TYPE = 'RemoteController/0/FocusControllerControlType'
        FOCUS_CONTROLLER_DIRECTION = 'RemoteController/0/FocusControllerDirection'
        FOCUS_CONTROLLER_IS_WORKING = 'RemoteController/0/FocusControllerIsWorking'
        FUNCTION_BUTTON = 'RemoteController/0/FunctionButton'
        GET_MASTER_AUTH_CODE = 'RemoteController/0/GetMasterAuthCode'
        GIMBAL_CONTROL_SPEED_COEFFICIENT = 'RemoteController/0/GimbalControlSpeedCoefficient'
        GIMBAL_MAPPING_STYLE = 'RemoteController/0/GimbalMappingStyle'
        GO_HOME_BUTTON = 'RemoteController/0/GoHomeButton'
        GPS_DATA = 'RemoteController/0/GPSData'
        HDMI_OUTPUT_FORMAT = 'RemoteController/0/HDMIOutputFormat'
        HDMI_SYSTEM_SETTING_OUTPUT_ENABLED = 'RemoteController/0/HDMISystemSettingOutputEnabled'
        IS_CHARGE_REMAINING_LOW = 'RemoteController/0/IsChargeRemainingLow'
        IS_FOCUS_CONTROLLER_SUPPORTED = 'RemoteController/0/IsFocusControllerSupported'
        IS_MASTER_SLAVE_MODE_SUPPORTED = 'RemoteController/0/IsMasterSlaveModeSupported'
        IS_MASTER_SLAVE_MODE_V2_SUPPORTED = 'RemoteController/0/IsMasterSlaveModeV2Supported'
        IS_MASTER_SLAVE_MODE_V3_SUPPORTED = 'RemoteController/0/IsMasterSlaveModeV3Supported'
        IS_MASTER_SLAVE_MODE_V4_SUPPORTED = 'RemoteController/0/IsMasterSlaveModeV4Supported'
        LEFT_DIAL = 'RemoteController/0/LeftDial'
        LEFT_DIAL_GIMBAL_CONTROL_AXIS = 'RemoteController/0/LeftDialGimbalControlAxis'
        LEFT_STICK_VALUE = 'RemoteController/0/LeftStickValue'
        MASTER_LIST = 'RemoteController/0/MasterList'
        MASTER_SEARCHING_STATE = 'RemoteController/0/MasterSearchingState'
        MASTER_SLAVE_STATE = 'RemoteController/0/MasterSlaveState'
        MODE = 'RemoteController/0/Mode'
        MULTI_DEVICES_PAIRING_STATE = 'RemoteController/0/MultiDeviceAggregationState'
        MULTI_RC_APPS_COUNT = 'RemoteController/0/MultiRcAppsCount'
        MULTI_RC_APPS_ONLINE_STATE = 'RemoteController/0/MultiRcAppsOnlineState'
        MULTI_RC_CONTROL_AUTHORITY_SURPASS = 'RemoteController/0/MultiRcControlAuthoritySurpass'
        MULTI_RC_GIMBALS_CONTROL_AUTH_OWNER = 'RemoteController/0/MultiRcGimbalsControlAuthOwner'
        MULTI_RC_LOST_NOTICE = 'RemoteController/0/MultiRcLostNotice'
        MULTI_RC_RCS_COUNT = 'RemoteController/0/MultiRcRcsCount'
        MULTI_RC_RCS_ONLINE_STATE = 'RemoteController/0/MultiRcRcsOnlineState'
        NAME = 'RemoteController/0/Name'
        PAIRING_STATE = 'RemoteController/0/PairingState'
        PASSWORD = 'RemoteController/0/Password'
        PAUSE_BUTTON = 'RemoteController/0/PauseButton'
        PIP_POSITION = 'RemoteController/0/PIPPosition'
        PLAYBACK_BUTTON = 'RemoteController/0/PlaybackButton'
        RC_HAS_GIMBAL_CONTROL = 'RemoteController/0/RcHasGimbalControl'
        RC_INDEX = 'RemoteController/0/RcIndex'
        RC_MASTER_SLAVE_OPEN = 'RemoteController/0/RcMasterSlaveOpen'
        RC_UPGRADE_VOICE_DISABLE = 'RemoteController/0/remote_controller_voice_disable'
        RECORD_BUTTON = 'RemoteController/0/RecordButton'
        RECORD_BUTTON_BINDING_ENABLED = 'RemoteController/0/RecordButtonBindingEnabled'
        REMOTE_CONTROLLER_CALIBRATION_A_AXIS_STATUS = 'RemoteController/0/RemoteControllerAAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_B_AXIS_STATUS = 'RemoteController/0/RemoteControllerBAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_C_AXIS_STATUS = 'RemoteController/0/RemoteControllerCAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_D_AXIS_STATUS = 'RemoteController/0/RemoteControllerDAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_E_AXIS_STATUS = 'RemoteController/0/RemoteControllerEAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_F_AXIS_STATUS = 'RemoteController/0/RemoteControllerFAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_G_AXIS_STATUS = 'RemoteController/0/RemoteControllerGAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_H_AXIS_STATUS = 'RemoteController/0/RemoteControllerHAxisStatus'
        REMOTE_CONTROLLER_CALIBRATION_NUMBER_OF_SEGMENT = 'RemoteController/0/RemoteControllerCalibrationNumberOfFragment'
        REMOTE_CONTROLLER_UNIT = 'RemoteController/0/remote_controller_unit_rc'
        REMOVE_BUTTON_PROFILE_GROUP = 'RemoteController/0/delete_user_for_professional_rc'
        RENAME_BUTTON_PROFILE_GROUP = 'RemoteController/0/change_user_name_of_professional_rc'
        REQUEST_GIMBAL_CONTROL = 'RemoteController/0/RequestGimbalControl'
        REQUEST_LEGACY_GIMBAL_CONTROL = 'RemoteController/0/RequestLegacyGimbalControl'
        RESET_BUTTON_CONFIG = 'RemoteController/0/reset_professional_rc'
        RESPONSE_TO_REQUEST_FOR_GIMBAL_CONTROL = 'RemoteController/0/ResponseToRequestForGimbalControl'
        RIGHT_DIAL = 'RemoteController/0/RightDial'
        RIGHT_STICK_VALUE = 'RemoteController/0/RightStickValue'
        RTK_CHANNEL_ENABLE = 'RemoteController/0/RTKChannelEnable'
        SDI_OUTPUT_FORMAT = 'RemoteController/0/SDIOutputFormat'
        SECONDARY_VIDEO_DISPLAY_MODE = 'RemoteController/0/SecondaryVideoDisplayMode'
        SECONDARY_VIDEO_OSD_BOTTOM_MARGIN = 'RemoteController/0/SecondaryVideoOSDBottomMargin'
        SECONDARY_VIDEO_OSD_ENABLED = 'RemoteController/0/SecondaryVideoOSDEnabled'
        SECONDARY_VIDEO_OSD_LEFT_MARGIN = 'RemoteController/0/SecondaryVideoOSDLeftMargin'
        SECONDARY_VIDEO_OSD_RIGHT_MARGIN = 'RemoteController/0/SecondaryVideoOSDRightMargin'
        SECONDARY_VIDEO_OSD_TOP_MARGIN = 'RemoteController/0/SecondaryVideoOSDTopMargin'
        SECONDARY_VIDEO_OSD_UNIT = 'RemoteController/0/SecondaryVideoOSDUnits'
        SECONDARY_VIDEO_OUTPUT_ENABLED = 'RemoteController/0/SecondaryVideoOutputEnabled'
        SECONDARY_VIDEO_OUTPUT_PORT = 'RemoteController/0/SecondaryVideoOutputPort'
        SELECT_BUTTON_PROFILE = 'RemoteController/0/current_config_index_of_current_user'
        SELECT_BUTTON_PROFILE_GROUP = 'RemoteController/0/current_user_of_professional_rc'
        SERIAL_NUMBER = 'RemoteController/0/SerialNumber'
        SET_MASTER_AUTH_CODE = 'RemoteController/0/SetMasterAuthCode'
        SHAKE_MOTOR = 'RemoteController/0/shakeMotor'
        SHUTTER_BUTTON = 'RemoteController/0/ShutterButton'
        SHUTTER_BUTTON_BINDING_ENABLED = 'RemoteController/0/ShutterButtonBindingEnabled'
        SLAVE_LIST = 'RemoteController/0/SlaveList'
        SLAVE_REMOTE_CONTROLLER_STICK_MODE = 'RemoteController/0/SlaveRemoteControllerStickMode'
        START_MULTI_DEVICE_PAIRING = 'RemoteController/0/StartMultiDevicePairing'
        START_PAIRING = 'RemoteController/0/StartPairing'
        START_SEARCH_MASTER = 'RemoteController/0/StartSearchMaster'
        STOP_MASTER_SEARCHING = 'RemoteController/0/StopMasterSearching'
        STOP_MULTI_DEVICE_PAIRING = 'RemoteController/0/StopMultiDevicePairing'
        STOP_PAIRING = 'RemoteController/0/StopPairing'
        TRANSFORMATION_SWITCH = 'RemoteController/0/TransformationSwitch'

    class MavicMaxLocal(Enum):
        TRACKER_ESTIMATOR_LOC = "Customvalue/Tracker/Estimator"
        TRACKER_DELAY = "Customvalue/Tracker/Delay"
        TRACKER_SPEED = "Customvalue/Tracker/TSpeed"
        TRACKER_COURSE = "Customvalue/Tracker/TCOURSE"
        TRACKER_DEBUG = "Customvalue/Tracker/Debug"
        LAST_MESSAGE = "Customvalue/Msg/Last"
        WINDSPEED = 'Customvalue/Windmeter/Windspeed'
        PHOTO_COUNTER = 'Customvalue/Photo/PhotosTaken'
        DEBUG1 = "Customvalue/Debug/Debug1"
        DEBUG2 = "Customvalue/Debug/Debug2"

    class MavicMaxApp(Enum):
        ACTIVETRACK_STATE = "Customvalue/Activetrack/State"
        ACTIVETRACK_TARGET_TYPE = "Customvalue/Activetrack/TargetType"
        VIRTUALSTICKS_STATE = "Customvalue/Virtualsticks/State"

    class MavicMaxCalculated(Enum):
        MPG = "Calculated/Mpg"
        POWER = "Calculated/Power"
        GIMBAL_YAW_DIFF = '"Calculated/GimbalYawDiff"'
        SPEED = "Calculated/Speed"
        GPS_DRONE_DIFF = "Calculated/GpsDroneDiff"
        DIST_LEFT = "Calculated/DistanceLeft"
        COURSE = "Calculated/Course"
        LEFT_STICK_X_VALUE = "Calculated/LeftStickX"
        DISTANCE_HOME_POINT = "Calculated/DistanceHomePoint"
        TRACKER_DISTANCE = "Calculated/TrackerDistance"

    class Hidden(Enum):
        MPG = "Customfunction/Mpg"
        POWER = "Customfunction/Power"
        SPEED = "Customfunction/Speed"
        GPS_DRONE_DIFF = "Customfunction/GpsDroneDiff"
        DIST_LEFT = "Customfunction/DistanceLeft"
        COURSE = "Customfunction/Course"
        MOTOR_PERCENTAGE = "Customfunction/MotorPercentage"
        MOTOR_RPM = "Customfunction/MotorRpm"
        RC_WIND = "Customfunction/Wind"
        RC_FCC = "Customfunction/RcInfo2"
        RC_AREA_CODE = "Customfunction/RcAreaCode"
        FLYC_LIMITS = "Customfunction/Limits"
        RC_BAT_PERCENTAGE = "Customfunction/RcBatPercentage"
        FLYC_PAR_TEST = "Customfunction/FlycParTest"
        SPEED_X = "Customfunction/SpeedX"
        SPEED_Y = "Customfunction/SpeedY"
        SPEED_Z = "Customfunction/SpeedZ"
        HEIGHT = "Customfunction/Height"
        HEIGHT_ULTRASONIC = "Customfunction/UltrasonicHeight"
        DRONETYPE = "Customfunction/DroneType"
        IS_SDK_ACTIVATED = "Customfunction/IsSdkActivated"
        GET_SDK_CONFIG_FILE = "Customfunction/GetSdkConfigFile"
        GET_SDK_TEST_URL = "Customfunction/GetSdkTestUrl"
        DEBUG1 = "Customfunction/Debug1"
        DEBUG2 = "Customfunction/Debug2"
        DEBUG3 = "Customfunction/Debug3"
        DEBUG4 = "Customfunction/Debug4"
        APP_FLAG = "Customfunction/AppFlag"
        PARAMETER = "Customfunction/Parameter"
        TRANSCODING_DATA_RATE = "Customfunction/TranscodingDataRate"



    @classmethod
    def get_short_name(cls, key):
        mapping = {'Latitude': 'Lat',
                   'Longitude': 'Lon',
                   'Location': '',
                   'Aircraft': '',
                   'Attitude': 'Att',
                   'Battery':'Bat',
                   'Available':'Avail',
                   'Percentage': '%',
                   'Needed': '',
                   'Remaining': 'Rem',
                   'TimeInSeconds': '',
                   'Recording': 'Rec',
                   'Radius': 'Rad',
                   'ToGoHome': 'RTH',
                   'String': ''

                   }
        parameter_name = key.value.split('/')[-1]
        for k, v in mapping.items():
            parameter_name = parameter_name.replace(k, v)
        if len(parameter_name)>13:
            parameter_name = parameter_name[:13]
        return parameter_name

    @classmethod
    def get_all_keys(cls) -> [str]:
        ret=[]
        for name, obj in inspect.getmembers(Keys):
            if inspect.isclass(obj):
                try:
                    for i in obj:
                        ret.append(i.value)
                except:
                    pass
        return ret


''' TODO Add more keys! 
def run(api: MavicMaxLib.Api, speed: float) -> str:
    keys_loop = [("dji.keysdk.BatteryKey", 'BatteryKey'),
                 ("dji.keysdk.FlightControllerKey", 'FlightControllerKey'),
                 ("dji.keysdk.DiagnosticsKey", 'DiagnosticsKey'),
                 ("dji.keysdk.CameraKey", 'CameraKey'),
                 ("dji.keysdk.GimbalKey", 'GimbalKey'),
                 ("dji.keysdk.RemoteControllerKey", 'RemoteControllerKey')]
                 ("com.plainembedded.mavicmax.drone.CustomKeyFunctions", 'Customfunction')]

    print("class Keys:")
    for (k, v) in keys_loop:
        print("\tclass " + v + "(Enum):")
        keys = api.drone.get_key_values(k).strip(",")
        for i in keys.split(','):
            key = i.split(' ')[0]
            value = i.split(' ')[1]
            print("\t\t{} = '{}/0/{}'".format(key, v.replace('Key', ''), value))

        print("")
        print("")
    return "OK"


if __name__ == "__main__":
    result = run(MavicMaxLib.get_instance(MavicMaxLib.Api.Mode.Rpc, "192.168.1.98"), 12)

'''




if __name__ == "__main__":
    print(Keys.get_short_name(Keys.FlightController.ATTITUDE_ROLL))
    print(Keys.get_short_name(Keys.FlightController.AIRCRAFT_LOCATION_LATITUDE))
    print(Keys.get_short_name(Keys.FlightController.ATTITUDE_YAW))
    print(Keys.get_short_name(Keys.FlightController.HOME_LOCATION_LATITUDE))
    print(Keys.get_short_name(Keys.Battery.VOLTAGE))
    print(Keys.get_short_name(Keys.Battery.CELL_VOLTAGES))
    print(Keys.get_short_name(Keys.Gimbal.ATTITUDE_IN_DEGREES))
    print(Keys.get_short_name(Keys.FlightController.ATTITUDE_ROLL))
    print(Keys.get_short_name(Keys.FlightController.ATTITUDE_ROLL))
    a = Keys.MavicMaxCalculated.POWER
    b = Keys.FlightController.ALTITUDE
    print(isinstance(b, Keys.MavicMaxCalculated))
    for i in Keys.Battery:
        print(i.name, i.value)
    l = [(i.name, i.value) for i in Keys.Battery]
    print(l)
    print("START")
    print( Keys.get_all_keys() )




